RIDES = [
    {
        "name": "Thunderbolt",
        "category": "Roller Coaster",
        "thrill_level": "High",
        "max_hourly_capacity": 800,
        "avg_ride_duration_min": 3,
        "breakdown_probability": 0.05,
        "weather_dependency": None,
    },
    {
        "name": "Aqua Rush",
        "category": "Water Ride",
        "thrill_level": "Medium",
        "max_hourly_capacity": 600,
        "avg_ride_duration_min": 5,
        "breakdown_probability": 0.03,
        "weather_dependency": "closes_on_rain",
    },
    {
        "name": "Free Fall Tower",
        "category": "Drop Tower",
        "thrill_level": "High",
        "max_hourly_capacity": 300,
        "avg_ride_duration_min": 2,
        "breakdown_probability": 0.04,
        "weather_dependency": None,
    },
    {
        "name": "Carousel",
        "category": "Family",
        "thrill_level": "Low",
        "max_hourly_capacity": 1200,
        "avg_ride_duration_min": 4,
        "breakdown_probability": 0.01,
        "weather_dependency": None,
    },
    {
        "name": "Bumper Cars",
        "category": "Family",
        "thrill_level": "Low",
        "max_hourly_capacity": 700,
        "avg_ride_duration_min": 6,
        "breakdown_probability": 0.02,
        "weather_dependency": None,
    },
    {
        "name": "Haunted Mansion",
        "category": "Dark Ride",
        "thrill_level": "Medium",
        "max_hourly_capacity": 900,
        "avg_ride_duration_min": 8,
        "breakdown_probability": 0.02,
        "weather_dependency": None,
    },
    {
        "name": "Mini Coaster",
        "category": "Kids Only",
        "thrill_level": "Low",
        "max_hourly_capacity": 1000,
        "avg_ride_duration_min": 3,
        "breakdown_probability": 0.01,
        "weather_dependency": None,
    },
]

RIDE_NAMES = [r["name"] for r in RIDES]
